### ISSUE TITLE
Kompatibilität mit Contao 3.5

### ISSUE THREAD

**Issue by jenda77** [cliffparnitzky/BirthdayMailer#6]
Lieber Cliff, 

wird es bald eine neue Version für 3.5.x geben? Im Composer wird mir gezeigt: "Diese Paket-Version ist mit dieser Contao-Version nicht kompatibel!"

Liebe Grüße,

Jan
<img width="923" alt="snimek obrazovky 2015-11-27 v 16 05 58" src="https://cloud.githubusercontent.com/assets/3715050/11443849/d289fb92-9520-11e5-8d1e-efe8f9e593f2.png">

**Comment by cliffparnitzky** [comment]
ich mach dazu mal nen Testbranch fertig, dann kannst du prüfen, ob alles geht.

**Comment by jenda77** [comment]
Danke für die schnelle Reaktion.

**Comment by cliffparnitzky** [comment]
Dann installiere mal den "support/contao3.5"

**Comment by jenda77** [comment]
Danke. Es tut mir leid, aber ich weiß es nicht, wie ich das installieren kann. Kann man nicht die ganze Version kompatibel mit Contao 3.5.x machen? Liebe Grüße, Jan

**Comment by cliffparnitzky** [comment]
Einfach im Composer den hier auswählen: 

![screen](https://cloud.githubusercontent.com/assets/1247552/11792068/7efc7fc2-a2a4-11e5-8596-c51b03950a78.jpg)

Die sollte kompatibel mit 3.5 sein.

**Comment by jenda77** [comment]
Danke. Leider verstehe ich nicht ganz, wie man eigene Texte hinbekommt - ich habe zwar die Anleitung durchgelesen, aber ich dachte, dass ich dafür ein Modul im Backend finde, damit das für die Redakteure verfügbar ist. So scheint mir das leider nicht nützlich zu sein oder habe ich etwas übersehen? Der Kunde möchte immer ein aktuelles Angebot an dessen Kunden verschicken, sobald diese Geburtstag haben. Dafür gibt es ein Formular, um die Daten zu sammeln (siehe http://babymanufactur.ppam.de). Es kann sein, dass ich es doch nicht mit deiner Erweiterung umsetzen kann? Momentan sehe ich da nicht die erhoffte Verwaltung in Backend. Aber es kann sein, dass ich das wirklich übersehen habe. :-)

**Comment by cliffparnitzky** [comment]
In der 1er Version können die Texte nur auf Dateiebene geändert werden. Deshalb wurde bereits die Arbeit an der 2er Version (https://github.com/cliffparnitzky/BirthdayMailer/milestones/2.0.0) begonnen. In der wird dann die Verwaltung der Text via Notification Center möglich sein. Wann die Version soweit ist, kann ich aktuell aber nicht sagen.

**Comment by cliffparnitzky** [comment]
ist mit Version 1.3.2 umgesetzt
